### PR TITLE
feat(recommend): Update demo and add credentials back

### PR DESCRIPTION
**Pull request by SophieManley03**
## What?
With the introduction of trends we want to be able to see it in the demo. 
Add credentials back.

## How?
In this PR we update the type for the model used.
We use 2 new components: trendingItems and trendingFacets. When we click on a trending facet we update trendingItems to display the trending items per facets

### CODE REVIEW

**Review by PLNech — COMMENTED** [review]
The code looks good to me :+1: However, I'm getting the following error when running either `yarn start` or `yarn build`:
```                                                                                                                                                                          9:57:07  ☁  feat/demo ☂ ✭
yarn run v1.22.18
$ parcel index.html
Error: Got unexpected undefined
    at nullthrows (/home/pln/Work/Clients/recommend/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/RequestTracker.js:245:44)
    at loadRequestGraph (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/RequestTracker.js:831:18)
    at async Function.init (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/RequestTracker.js:792:17)
    at async Parcel._init (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/Parcel.js:481:50)
    at async Parcel.watch (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/Parcel.js:567:7)
    at async run (/home/pln/Work/Clients/recommend/node_modules/parcel/lib/cli.js:352:9) {
  framesToPop: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Likewise with `yarn start`:
```
yarn run v1.22.18
$ parcel index.html
Error: Got unexpected undefined
    at nullthrows (/home/pln/Work/Clients/recommend/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/RequestTracker.js:245:44)
    at loadRequestGraph (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/RequestTracker.js:831:18)
    at async Function.init (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/RequestTracker.js:792:17)
    at async Parcel._init (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/Parcel.js:481:50)
    at async Parcel.watch (/home/pln/Work/Clients/recommend/node_modules/@parcel/core/lib/Parcel.js:567:7)
    at async run (/home/pln/Work/Clients/recommend/node_modules/parcel/lib/cli.js:352:9) {
  framesToPop: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Any idea what could be causing this?

**Comment by Haroenv** [comment]
https://github.com/parcel-bundler/parcel/issues/5196 @PLNech

**Comment by PLNech** [comment]
Thanks @Haroenv! Indeed either with `--no-cache` or on a fresh git clone, the build works as expected. :relieved:

**Comment by PLNech** [comment]
Now running fine the demo, looks good!
I got an error from Trending when I selected a blue scarf : 


Unsure if that's expected :shrug:

**Comment by SophieManley03** [comment]
@PLNech  Yes for now it's expected the model is not trained yet as we are missing some events at the moment.

**Review by PLNech — APPROVED** [review]
Looks good to me :rocket:

**Pull request merged**
